#                   __ _       
#   ___ ___  _ __  / _(_) __ _ 
#  / __/ _ \| '_ \| |_| |/ _` |
# | (_| (_) | | | |  _| | (_| |
#  \___\___/|_| |_|_| |_|\__, |
#                        |___/ 
#---------------------------------------------------------------------
#  _____________ 
# < fill me out >
#  ------------- 
#         \   ^__^
#          \  (oo)\_______
#             (__)\       )\/\
#                 ||----w |
#                 ||     ||
#---------------------------------------------------------------------

# Main Inventory Feed
#   Place path to QuickBooks (or other) inventory export csv here:
path_to_main_feed: ""
#   Place column data for feed here (SKU, QTY):
feed_cols: ['Item', 'Quantity On Hand']

# Email Account Info 
#   Place your email info here:  
sender_info:
  SENDER_EMAIL: ""
  EMAIL_PASSWORD: ""
  SMTP_SERVER: ""
  SERVER_PORT: 

# FTP Info
#   If applicable please place information for ftp server you wish to 
#   upload to here:
ftp_info:
  FTP_HOST: ""
  FTP_USER: ""
  FTP_PASSWORD: ""
  FTP_UPLOAD_PATH: ""

# Company Name
#   This will be used in emails that are sent:
company_name: ""
# Email Body Text
#   Customize how you would like your email text to appear here:
body_greeting: "Hi"
body_text: "Attached is an updated inventory feed of our products."
body_closer: "Best Regards,"

# Email Recipients
#   Place information for where emails should be sent here.
#   *IMPORTANT* The first field (sitename-single-word) should match the identifier set in 'Site Info' (below). 
#   Format = "sitename-single-word": ["receiver_email_address", "Site Name", "Name of Email Recipient"]
#      e.g.  "bigdropshipsite": ["inventory@bigdropshipsite.com", "Big Dropship Site", "Jenny"]
receiver_info:
    "sitename-single-word": ["receiver_email_address", "Site Name", "Name of Email Recipient"]
    "sitename-single-word": ["receiver_email_address", "Site Name", "Name of Email Recipient"]
    "sitename-single-word": ["receiver_email_address", "Site Name", "Name of Email Recipient"]

#---------------------------------------------------------------------
# inv_feed info:
#---------------------------------------------------------------------

# Site Info
#   Place infomation about sites and their inventory feed columns here.
#   *IMPORTANT* The first field (sitename-single-word) should match the identifier set in 'Email Recipients' (above).
#   Format = "sitename-single-word": ["SKU Column Title", "Quantity Column Title", "extra-params (if applicable)"]
#      e.g.  "bigdropshipsite": ["Item", "QTY"]
site_dic:
    "sitename-single-word": ["Item Number", "Qty On Hand"]
    "sitename-single-word": ["SKU", "QTY Available"]
    "sitename-single-word": ["SKU", "Current Inventory Level"]

# OPTIONAL: Backorder Info
#   Place sites that require backorder dates here.
#   *IMPORTANT* "sitename-single-word" should match identifiers above.
backorder_site_list: 
  - "sitename-single-word"
  - "sitename-single-word"
  - "sitename-single-word"
#   Place backorder column titles from applicable inventory templates here
backorder_cols: 
  - "Stock Next Expected"
  - "Next In-Stock Date"
  - "Restock Date"
  - "Next Available Date"
  - "Item Next Availability Date"
  - "Back order ETA"
#   Place discontinued column titles from applicable inventory templates here
discontinued_cols:
  - "Discontinued?"
  - "Discontinue Date"
  - "Item Discontinued "
#   Number of months from date of creation to set as backorder date
months: 3
#   Number of days before backorder date to renew backorder date, if item still out of stock
days: 1

# OPTIONAL: Rearrange Info
#   *IMPORTANT* "sitename-single-word" should match identifiers above.
#   Place sites that need column swapping and column index to swap here.
rearrange_dic:
  "sitename-single-word": [0,1]

# OPTIONAL: Multiple Feed Single Site Info
#   *IMPORTANT* "sitename-single-word" should match identifiers above.
#   Place sites that need seperate feeds generated for each brand and applicable brands here:
multi_brand_dic:
  "sitename-single-word": ["brand1", "brand2", "brand3"]

